### ISSUE TITLE
Error STAR 

### ISSUE THREAD

**Issue by alessandriLuca** [SpatialTranscriptomicsResearch/st_pipeline#111]
Good morning, first of all i would like to congrats for the pipeline and the work done! I think that this is very useful! Im trying to run the test but after the script load successfully all the data then i receive this error : 

[log_file.txt](https://github.com/SpatialTranscriptomicsResearch/st_pipeline/files/3481295/log_file.txt)

This is the way in which im calling the function : 
`python3 st_pipeline_run.py --expName test --ids /data2/st_pipeline-master/ids/1000L2_barcodes.txt --ref-map /data2/st_pipeline-master/tests/config/contaminant_genomes/R45S5_R5S1/ --log-file log_file.txt --output-folder /home/me/results --ref-annotation /data2/st_pipeline-master/tests/config/annotations/Homo_sapiens.GRCh38.79_chr19.gtf /data2/st_pipeline-master/tests/input/arrayjet_1002/testdata_R1.fastq /data2/st_pipeline-master/tests/input/arrayjet_1002/testdata_R2.fastq 
`
and im using all the data that are in your folders. 

Thanks in advance for your availability. 

Best

Luca

**Comment by jfnavarro** [comment]
Hi Luca! 

Thanks for your message. 

You need to have the aligner STAR installed in your system. 

https://github.com/alexdobin/STAR

**Comment by alessandriLuca** [comment]
Hi! Thats was a super fast answer! Thanks gonna install and try!

**Comment by alessandriLuca** [comment]
Hi Josè, so i just fixed STAR but i have another problem, 
```
ST Pipeline, parameters loaded
ST Pipeline, logger created
ST Pipeline, sanity check passed. Starting the run.
Error running the pipeline
Error mapping with STAR.
Output file not present /tmp/st_pipeline_temp4_tikme4/Aligned.sortedByCoord.out.bam
b'/tmp/st_pipeline_temp4_tikme4/_STARtmp//readsCommand_read1: 3: /tmp/st_pipeline_temp4_tikme4/_STARtmp//readsCommand_read1: samtools: not found\nsh: 1: samtools: not found\n\nEXITING because of FATAL ERROR: could not open genome file /data2/st_pipeline-master/tests/config/contaminant_genomes/R45S5_R5S1/genomeParameters.txt\nSOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions\n\nAug 08 13:18:23 ...... FATAL ERROR, exiting\n'
```
Maybe im using in the wrong way the example data that you have in github?

**Comment by jfnavarro** [comment]
As it says in the error message you also need to install samtools which is a requirement for STAR to work...

**Comment by alessandriLuca** [comment]
Hi Josè, as you can see from the picture samtools is already installed. 
![image](https://user-images.githubusercontent.com/6830335/62701469-a9905000-b9e4-11e9-9568-28114b083e5f.png)

Thank you again

**Comment by alessandriLuca** [comment]
Dear Josè, i tried several fix but i got still the same error, do you have some ideas?

**Comment by jfnavarro** [comment]
Are you able to run STAR and map some test file? What STAR version are you using?

**Comment by alessandriLuca** [comment]
Dear Josè, i reinstalled everything in order to be sure to have the right versions that you suggest in your tutorial. Right now with the same code 
`python3 st_pipeline_run.py --expName test --ids /data2/st_pipeline-master/ids/1000L2_barcodes.txt --ref-map /data2/st_pipeline-master/tests/config/contaminant_genomes/R45S5_R5S1/ --log-file log_file.txt --output-folder /home/me/results --ref-annotation /data2/st_pipeline-master/tests/config/annotations/Homo_sapiens.GRCh38.79_chr19.gtf /data2/st_pipeline-master/tests/input/arrayjet_1002/testdata_R1.fastq /data2/st_pipeline-master/tests/input/arrayjet_1002/testdata_R2.fastq
`

i have another error: 
`Output file not present /tmp/st_pipeline_tempciaq7pap/Aligned.sortedByCoord.out.bam
b'\nEXITING because of FATAL ERROR: could not open genome file /data2/st_pipeline-master/tests/config/contaminant_genomes/R45S5_R5S1/genomeParameters.txt\nSOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions\n\nAug 14 09:48:20 ...... FATAL ERROR, exiting\n'`

samtools and Star works Perfectly. Seems that i miss something in the genome directory but im using your example files.  Thank you again 

Best

Luca

**Comment by jfnavarro** [comment]
Ahhhh, I know what is going on. You need to create the genome indexes. I provide the .fasta files but you need to use STAR to create the genome indexes for the genome and the contaminant genome. The indexes will be composed of several files and folder and you need to pass the pipeline the path to the index's folder. Read the STAR documentation to know more about how to create indexes. It is straight forward. If you read the documentation it says that you need to pass a genome index not a fasta file as argument.

**Comment by alessandriLuca** [comment]
Oh ok! Yes i can create the genome index, i thought that would have been created from the script itself! Thank you ;)

**Comment by jfnavarro** [comment]
Oh no, you need to create the index only once. It would not be smart to let the pipeline create the index every time you run it. Okay, let me know if you manage to make it work so I can close the issue.

**Comment by alessandriLuca** [comment]
Yes you are right! Ok cool i will let you know ;) Thanks again!

**Comment by alessandriLuca** [comment]
Perfect is working!! Thank you again!
