### ISSUE TITLE
Question: are the intermediate BAM files saved?

### ISSUE THREAD

**Issue by Puriney** [SpatialTranscriptomicsResearch/st_pipeline#112]
Hello ST team,
I was wondering if the intermediate BAM files are saved somewhere?
Best,
Yun

**Comment by sjtlzh123** [comment]
I think the ST pipeline generates a bed file in the output folder and you can try to convert it to sam file using bedToSam function included in BEDtools.

**Comment by Puriney** [comment]
```
--temp-folder $TEMPDIR \
--no-clean-up 
```

By calling the arguments above, the pipeline saves the intermediate results including the BAM file I am asking here. It is saved '$TEMPDIR/annotated.bam'. Thank you for following up.
