### ISSUE TITLE
"cdistance.o" missing when building pipeline

### ISSUE THREAD

**Issue by fatimasnc** [SpatialTranscriptomicsResearch/st_pipeline#113]
Hi!

I am trying to install the ST pipeline and when I type the "python setup.py build" command I get the following error: 

"gcc -pthread -B /home/sfatima/miniconda3/envs/ST/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sfatima/miniconda3/envs/ST/include/python3.7m -c stpipeline/common/cdistance.c -o build/temp.linux-x86_64-3.7/stpipeline/common/cdistance.o
gcc: error: stpipeline/common/cdistance.c: No such file or directory
error: command 'gcc' failed with exit status 1"

I tried to find such file and could only come across "cdistance.pyx" in that location. Could it be that "cdistance.c" is accidentally missing after some update? I checked the GitHub repository itself and it's also not there. 

Thanks a lot for your help!

Best,
Fátima

**Comment by sjtlzh123** [comment]
I think Cython will generate cdistnace.c from cdistance.pyx. Have you properly installed Cython?
