### ISSUE TITLE
Extract allele specific matrices

### ISSUE THREAD

**Issue by WT215** [SpatialTranscriptomicsResearch/st_pipeline#116]
Hello,

I have spatial transcriptome data from mouse C57BL6 X CAST.

Can this pipeline also be used to generate allele specific gene expression matrix? So that there will be two matrices of the same dimension (gene*spot), where each element in the matrix (UMI count) correspond to cast or c57 alleles?

Thanks a lot!

**Comment by jfnavarro** [comment]
Hello and I apologize for the late reply. 

Currently, this option is not available. 

Best

**Comment by WT215** [comment]
Ok I see. Thanks a lot!
