### ISSUE TITLE
overlay molecular data on top of tissue histology

### ISSUE THREAD

**Issue by WT215** [SpatialTranscriptomicsResearch/st_pipeline#117]
Hello,

Now I have a PNG of tissue histology and coordinates of spots. How could I overlay the molecular data on top of tissue histology like shown in Seurat's tutorial [https://satijalab.org/seurat/v3.1/spatial_vignette.html](https://satijalab.org/seurat/v3.1/spatial_vignette.html)?

Data come from [https://spatialtranscriptomics.com/resources/](https://spatialtranscriptomics.com/resources/)

Thanks a lot!

**Comment by haowBio** [comment]
I meet the same issue, how you deal with it?

**Comment by WT215** [comment]
> I meet the same issue, how you deal with it?

Use spaceranger to preprocess the fastq files (if you are using 10X visium).
