### ISSUE TITLE
Memory error while sorting bam

### ISSUE THREAD

**Issue by amdixit** [SpatialTranscriptomicsResearch/st_pipeline#120]
When I run the pipeline i received the following error:

b'\nEXITING: fatal error trying to allocate genome arrays, exception thrown: std::bad_alloc\nPossible cause 1: not enough RAM. Check if you have enough RAM 108847334315717446 bytes\nPossible cause 2: not enough virtual memory allowed with ulimit. SOLUTION: run ulimit -v 108847334315717446\n\nNov 10 03:07:12 ......FATAL ERROR, exiting\n'

I try to limit the memory used by passing the argument  star-sort-mem-limit like below but it did not help either! Please assist

st_pipeline_run.py \
  --output-folder $OUTPUT \
  --ids $ID \
  --ref-map $MAP \
  --ref-annotation $ANN \
  --expName $sample \
  --htseq-no-ambiguous \
  --verbose \
  --log-file $OUTPUT/${sample}_log.txt \
  --allowed-kmer 5 \
  --mapping-threads 20 \
  --temp-folder $TMP_ST \
  --no-clean-up \
  --umi-start-position 16 \
  --umi-end-position 26 \
  --star-sort-mem-limit 70166447416 \
  --overhang 0 \
  --min-length-qual-trimming 20 \

**Comment by amdixit** [comment]
full error:

ST Pipeline, parameters loaded
ST Pipeline, logger created
ST Pipeline, sanity check passed. Starting the run.
Error running the pipeline
Error mapping with STAR.
Output file not present /usr/bin/dbit/output/tmp/Aligned.sortedByCoord.out.bam
b'\nEXITING: fatal error trying to allocate genome arrays, exception thrown: std::bad_alloc\nPossible cause 1: not enough RAM. Check if you have enough RAM 108847334315717446 bytes\nPossible cause 2: not enough virtual memory allowed with ulimit. SOLUTION: run ulimit -v 108847334315717446\n\nNov 10 04:32:28 ......FATAL ERROR, exiting\n'

**Comment by jfnavarro** [comment]
Hello,

How much RAM memory do you have available in the machine that you are using?

Best,
Jose

**Comment by amdixit** [comment]
Turns out we had a corruption of genome files. The issue resolved after we fixed that. Thanks!
