### ISSUE TITLE
How can i get 'ids' file?

### ISSUE THREAD

**Issue by qijt123** [SpatialTranscriptomicsResearch/st_pipeline#128]
Hello!

Thank you very much for your work.

I have a problem. I'm analyzing ST data for an article called "Molecular Atlas ofthe Adult Mouse Brain," and I can't find the "IDS" file. Therefore, I wonder if I can directly use the "1000l9_barcodes.txt" you gave me as the input?

Looking forward to your reply.

Thank you very much!

**Comment by jfnavarro** [comment]
Hello,

The IDs files are stored in the "ids" folder as it says in the documentation.

Best,
Jose
